#include<stdio.h>
#include<stdlib.h>
#include<string.h>

#include"projectheader.h"
#include"user.h"



BookList* bgn=0;
Userlist *userbgn=0;


int store_books(FILE *file){
    Book* liststart=bgn->list->next;
   if (file == NULL ){
    printf("Error\nBook file does not exist: %s\n");
    exit(0);
}
while(bgn->list->next!=NULL){
    fprintf(file,"%d\n",bgn->list->next->id);
    fprintf(file,"%s\n",bgn->list->next->title);
    fprintf(file,"%s\n",bgn->list->next->authors);
    fprintf(file,"%d\n",bgn->list->next->year);
    fprintf(file,"%d\n",bgn->list->next->copies);
    bgn->list->next=bgn->list->next->next;
}
  bgn->list->next=liststart;
  return 0;
}

//loads the database of books from the specified file
//the file must have been generated by a previous call to store_books()
//returns 0 if books were loaded correctly, or an error code otherwise
int load_books(FILE *file){
    char buff[100];
     if (file == NULL ){
    printf("Error\nBook file does not exist: %s\n");
	return 1;
	exit(0);
     }
	 Book* bookfinal=(Book*)malloc(sizeof(Book));
	
	bgn=(BookList*)malloc(sizeof(BookList));
    bgn->list=bookfinal;
    bgn->length=0;
    char c=fgetc(file);
    
    if(c!=EOF){
        rewind(file);
    while (1)
	{		
        
		Book* book=(Book*)malloc(sizeof(Book));
		bookfinal->next=book;
        
        book->authors=(char *)malloc(100*sizeof(char));
        book->title=(char *)malloc(100*sizeof(char));
		book->history=(User*)malloc(sizeof(User));
        book->history->next=NULL;
      
        fgets(buff,100,file);
        if(feof(file)){
            break;
        }
        sscanf(buff,"%d\n", &book->id);
       
        fgets(buff,100,file);
         sscanf(buff,"\%[^\n]", book->title);
          
         fgets(buff,100,file);
         sscanf(buff,"\%[^\n]", book->authors);
           
         fgets(buff,100,file);
         sscanf(buff,"%d\n", &book->year);
           
            
         fgets(buff,100,file);
         sscanf(buff,"%d\n", &book->copies);
       
        
        book->borrowed=0;
        bgn->length+=1; 
        bookfinal=book;
        
	}
	bookfinal->next=NULL;
    
	return 0;
    }
    else{
        bgn->list->next=NULL;
        return 0;
    }
    
}

int load_user(FILE *file){
    char buff[100];
     if (file == NULL ){
    printf("Error\nUser file does not exist: %s\n");
	exit(0);
	
     }
	User* userfinal=(User*)malloc(sizeof(User));
	
	userbgn=(Userlist*)malloc(sizeof(Userlist));
    userbgn->list=userfinal;
    userbgn->length=0;
    char c=fgetc(file);
    if(c!=EOF){
        rewind(file);
    while (1)
	{		
        
		User* user1=(User*)malloc(sizeof(User));
		
       
        user1->name=(char *)malloc(100*sizeof(char));
        user1->password=(char *)malloc(100*sizeof(char));
		
       
         fgets(buff,100,file);
          if(feof(file)){
            break;
        }
         
         sscanf(buff,"\%[^\n]", user1->name);
      
        fgets(buff,100,file);
         sscanf(buff,"\%[^\n]", user1->password);
         userfinal->next=user1;
        user1->bookborrow=(Book*)malloc(sizeof(Book));
        user1->bookborrow->next=NULL;
        user1->number=0;
        userbgn->length+=1;
        userfinal=user1;
	}
    
	userfinal->next=NULL;
    
	return 0;
    }
    else{
        userbgn->list->next=NULL;        
        return 0;
    }
    
}



int store_user(FILE *file){
    User* userstart=userbgn->list->next;
   if (file == NULL ){
    printf("Error\nUser file does not exist: %s\n");
    exit(0);
}
while(userbgn->list->next!=NULL){
    fprintf(file,"%s\n",userbgn->list->next->name); 
    fprintf(file,"%s\n",userbgn->list->next->password);
    userbgn->list->next=userbgn->list->next->next;
}
  userbgn->list->next=userstart;
  return 0;
}


int load_history(FILE* file){
    Book* bookstart=bgn->list->next;
     char buff[100];
    while(bgn->list->next!=NULL){
        User* temp=bgn->list->next->history;
        fscanf(file,"%d\n", &bgn->list->next->borrowed);
        for(int i=0;i<bgn->list->next->borrowed;i++){
            User* new=(User*)malloc(sizeof(User));
             bgn->list->next->history->next=new;
            bgn->list->next->history->next->name=(char*)malloc(100*sizeof(char));
            fgets(buff,100,file);
            sscanf(buff,"\%[^\n]", bgn->list->next->history->next->name);
             
             new->next=NULL;
             
             bgn->list->next->history=new;
             
        }
        bgn->list->next->history=temp;
        bgn->list->next=bgn->list->next->next;
        
        
    }
    
    bgn->list->next=bookstart;
    return 0;
     
}



int store_history(FILE *file){ 
    while(bgn->list->next!=NULL){   
         fprintf(file,"%d\n",bgn->list->next->borrowed);
        while(bgn->list->next->history->next!=NULL){
             fprintf(file,"%s\n",bgn->list->next->history->next->name);
              bgn->list->next->history->next= bgn->list->next->history->next->next;           
        }  
        bgn->list->next=bgn->list->next->next;
    }
    return 0;
  
}
int load_borrow(FILE* file){
    char buff1[100];
    User* userstart=userbgn->list->next;
    while(userbgn->list->next!=NULL){
        Book* temp=userbgn->list->next->bookborrow;
         fscanf(file,"%d\n", &userbgn->list->next->number);
      
        for(int i=0;i<userbgn->list->next->number;i++){
        
            Book* new=(Book*)malloc(sizeof(Book));
               
             userbgn->list->next->bookborrow->next=new;
            userbgn->list->next->bookborrow->next->authors=(char*)malloc(100*sizeof(char));
            userbgn->list->next->bookborrow->next->title=(char*)malloc(100*sizeof(char));
            
        fgets(buff1,100,file);
        sscanf(buff1,"%d\n", &userbgn->list->next->bookborrow->next->id);
      
        fgets(buff1,100,file);
         sscanf(buff1,"\%[^\n]", userbgn->list->next->bookborrow->next->title);
       
         fgets(buff1,100,file);
         sscanf(buff1,"\%[^\n]", userbgn->list->next->bookborrow->next->authors);
       
         fgets(buff1,100,file);
         sscanf(buff1,"%d\n", &userbgn->list->next->bookborrow->next->year);
      
           
             new->next=NULL;
             
             userbgn->list->next->bookborrow=new;
             
        }
        userbgn->list->next->bookborrow=temp;
        userbgn->list->next=userbgn->list->next->next;
        
        
    
    }
    userbgn->list->next=userstart;
    return 0;
}

int store_borrowed(FILE *file){
    while(userbgn->list->next!=NULL){
        fprintf(file,"%d\n",userbgn->list->next->number);
       while(userbgn->list->next->bookborrow->next!=NULL){
            fprintf(file,"%d\n",userbgn->list->next->bookborrow->next->id);
            fprintf(file,"%s\n",userbgn->list->next->bookborrow->next->title);
             fprintf(file,"%s\n",userbgn->list->next->bookborrow->next->authors);
              fprintf(file,"%d\n",userbgn->list->next->bookborrow->next->year);
            userbgn->list->next->bookborrow->next=userbgn->list->next->bookborrow->next->next;
       }
       userbgn->list->next=userbgn->list->next->next;
    }
    return 0;
}



void closecil(FILE* book,FILE* user,FILE* history,FILE*borrow){
    
    store_books(book);
    
    store_user(user);
 
    store_history(history);
    
  store_borrowed(borrow);
    
    User* temp;
    Book* temp2;
    User * temp3;
    Book* temp4;
    while(userbgn->list->next!=NULL){
        while(userbgn->list->next->bookborrow->next!=NULL){
             temp4=userbgn->list->next->bookborrow->next;
             userbgn->list->next->bookborrow->next=userbgn->list->next->bookborrow->next->next;
             free(temp4);
        }
        temp=userbgn->list->next;
        userbgn->list->next=userbgn->list->next->next;
        free(temp);
    }
      
     while(bgn->list->next!=NULL){
          while(bgn->list->next->history->next!=NULL){
            temp3=bgn->list->next->history->next;
            bgn->list->next->history->next=bgn->list->next->history->next->next;
            free(temp3);
        }
         free(bgn->list->next->history);
        temp2=bgn->list->next;
        bgn->list->next=bgn->list->next->next;
        free(temp2);
        
    }
    
   
    free(userbgn->list);
    free(bgn->list);
    free(bgn);
    free(userbgn);
   
}

