#include<stdio.h>
#include<stdlib.h>
#include<string.h>

#include"bookmanagement.h"




BookList* bgn=0;
Userlist *userbgn=0;

int store_books(FILE *file){
     
    Book* liststart=bgn->list->next;
   if (file == NULL ){
    printf("Error\nBook file does not exist: %s\n");
    exit(0);
}
while(bgn->list->next!=NULL){
    fprintf(file,"%d\n",bgn->list->next->titlesize);
    fprintf(file,"%s\n",bgn->list->next->title);
   fprintf(file,"%d\n",bgn->list->next->authorsize);
    fprintf(file,"%s\n",bgn->list->next->authors);
    fprintf(file,"%d\n",bgn->list->next->year);
    fprintf(file,"%d\n",bgn->list->next->copies);
       fprintf(file,"%d\n",bgn->list->next->borrowing);
    bgn->list->next=bgn->list->next->next;
}
  bgn->list->next=liststart;
  return 0;
}





//loads the database of books from the specified file
//the file must have been generated by a previous call to store_books()
//returns 0 if books were loaded correctly, or an error code otherwise
int load_books(FILE *file){
    char buff[100];
    int a=1;
    int bookid;
     if (file == NULL ){
    printf("Error\nBook file does not exist: %s\n");
	return 1;
	exit(0);
     }
	 Book* bookfinal=(Book*)malloc(sizeof(Book));
	
	bgn=(BookList*)malloc(sizeof(BookList));
    bgn->list=bookfinal;
    bgn->length=0;
    char c=fgetc(file);
   
    if(c!=EOF){
        rewind(file);
    while (1)
	{		
		Book* book=(Book*)malloc(sizeof(Book));
		bookfinal->next=book;
        
      
      
		book->history=(User*)malloc(sizeof(User));
        book->history->next=NULL;
       book->id=a;
        a+=1;
         fgets(buff,100,file);
         if(feof(file)){
            break;
        }
         sscanf(buff,"%d", &book->titlesize);
        book->title=(char *)malloc((book->titlesize)*sizeof(char));

        fgets(buff,100,file);
         sscanf(buff,"%[^\n]", book->title);

            fgets(buff,100,file);
          sscanf(buff,"%d", &book->authorsize);
        book->authors=(char *)malloc((book->authorsize)*sizeof(char));
          
         fgets(buff,100,file);
         sscanf(buff,"%[^\n]", book->authors);
           
         fgets(buff,100,file);
         sscanf(buff,"%d\n", &book->year);

         fgets(buff,100,file);
         sscanf(buff,"%d\n", &book->copies);
        fgets(buff,100,file);
         sscanf(buff,"%d\n", &book->borrowing);
       
        
        book->borrowed=0;
        bgn->length+=1; 
        bookfinal=book;  
       
	}
     
	bookfinal->next=NULL;
   
	return 0;
    }
    else{
        bgn->list->next=NULL;
        return 0;
    }
    
}




int load_user(FILE *file){
    char buff[100];
     if (file == NULL ){
    printf("Error\nUser file does not exist: %s\n");
	exit(0);
	
     }
	User* userfinal=(User*)malloc(sizeof(User));
	
	userbgn=(Userlist*)malloc(sizeof(Userlist));
    userbgn->list=userfinal;
    userbgn->length=0;
    char c=fgetc(file);
    
    if(c!=EOF){
        rewind(file);
    while (1){		
		User* user1=(User*)malloc(sizeof(User));    
		 fgets(buff,100,file);
          if(feof(file)){
            break;
        }
         sscanf(buff,"%d", &user1->namesize);
        user1->name=(char *)malloc((user1->namesize)*sizeof(char));
         fgets(buff,100,file);
         sscanf(buff,"%[^\n]", user1->name);
          fgets(buff,100,file);
         sscanf(buff,"%d", &user1->passwordsize);
          user1->password=(char *)malloc((user1->passwordsize)*sizeof(char));
        fgets(buff,100,file);
         sscanf(buff,"%[^\n]", user1->password);
         userfinal->next=user1;
        user1->bookborrow=(Book*)malloc(sizeof(Book));
        user1->bookborrow->next=NULL;
        user1->number=0;
        userbgn->length+=1;
        userfinal=user1;
	}
    
	userfinal->next=NULL;
    
	return 0;
    }
    else{
        userbgn->list->next=NULL;        
        return 0;
    }
    
}




int store_user(FILE *file){
    
    User* userstart=userbgn->list->next;
   if (file == NULL ){
    printf("Error\nUser file does not exist: %s\n");
    exit(0);
}

while(userbgn->list->next!=NULL){
   
     fprintf(file,"%d\n",userbgn->list->next->namesize); 
    fprintf(file,"%s\n",userbgn->list->next->name); 
     
     fprintf(file,"%d\n",userbgn->list->next->passwordsize); 
    fprintf(file,"%s\n",userbgn->list->next->password);
    userbgn->list->next=userbgn->list->next->next;
}
  userbgn->list->next=userstart;
  return 0;
}




int load_history(FILE* file){

    char c=fgetc(file);
   
    if(c!=EOF){
        rewind(file);
    
    Book* bookstart=bgn->list->next;
     char buff[100];
    while(bgn->list->next!=NULL){
        User* temp=bgn->list->next->history;
        fscanf(file,"%d\n", &bgn->list->next->borrowed);
        for(int i=0;i<bgn->list->next->borrowed;i++){
            User* new=(User*)malloc(sizeof(User));
             bgn->list->next->history->next=new;
              fgets(buff,100,file);
            sscanf(buff,"%d", &bgn->list->next->history->next->namesize);
            bgn->list->next->history->next->name=(char*)malloc((bgn->list->next->history->next->namesize)*sizeof(char));
            fgets(buff,100,file);
            sscanf(buff,"%[^\n]", bgn->list->next->history->next->name);
           
             new->next=NULL;
             bgn->list->next->history=new;
             
        }
         
        bgn->list->next->history=temp;
        bgn->list->next=bgn->list->next->next;
       
        
    }
    
    bgn->list->next=bookstart;
    return 0;
    }
    else{
        return 1;
    }
}




int store_history(FILE *file){ 
     
    while(bgn->list->next!=NULL){   
         fprintf(file,"%d\n",bgn->list->next->borrowed);
        while(bgn->list->next->history->next!=NULL){
              fprintf(file,"%d\n",bgn->list->next->history->next->namesize);
             fprintf(file,"%s\n",bgn->list->next->history->next->name);
            
              bgn->list->next->history->next= bgn->list->next->history->next->next;           
        }  
        bgn->list->next=bgn->list->next->next;
    }
    return 0;
  
}





int load_borrow(FILE* file){
     char c=fgetc(file);
    
    if(c!=EOF){
        rewind(file);
    }
    else{
        
        return 0;
    }
    char buff1[100];
    User* userstart=userbgn->list->next;
    
    while(userbgn->list->next!=NULL){
       
        Book* temp=userbgn->list->next->bookborrow;
         fscanf(file,"%d\n", &userbgn->list->next->number);
         
        for(int i=0;i<userbgn->list->next->number;i++){
        
            Book* new=(Book*)malloc(sizeof(Book));
               
             userbgn->list->next->bookborrow->next=new;
                  
        fgets(buff1,100,file);
        sscanf(buff1,"%d\n", &userbgn->list->next->bookborrow->next->id);
       fgets(buff1,100,file);
        sscanf(buff1,"%d\n", &userbgn->list->next->bookborrow->next->titlesize);
         userbgn->list->next->bookborrow->next->title=(char*)malloc((userbgn->list->next->bookborrow->next->titlesize)*sizeof(char));
        fgets(buff1,100,file);
         sscanf(buff1,"\%[^\n]", userbgn->list->next->bookborrow->next->title);

            fgets(buff1,100,file);
        sscanf(buff1,"%d\n", &userbgn->list->next->bookborrow->next->authorsize);
        userbgn->list->next->bookborrow->next->authors=(char*)malloc((userbgn->list->next->bookborrow->next->authorsize)*sizeof(char));
       
         fgets(buff1,100,file);
         sscanf(buff1,"\%[^\n]", userbgn->list->next->bookborrow->next->authors);
       
         fgets(buff1,100,file);
         sscanf(buff1,"%d\n", &userbgn->list->next->bookborrow->next->year);
      
           
             new->next=NULL;
             
             userbgn->list->next->bookborrow=new;
             
        }
        userbgn->list->next->bookborrow=temp;
        userbgn->list->next=userbgn->list->next->next;
        
        
    
    }
    userbgn->list->next=userstart;
    return 0;
}




int store_borrowed(FILE *file){
   
    while(userbgn->list->next!=NULL){
        fprintf(file,"%d\n",userbgn->list->next->number);
       while(userbgn->list->next->bookborrow->next!=NULL){
            fprintf(file,"%d\n",userbgn->list->next->bookborrow->next->id);
             fprintf(file,"%d\n",userbgn->list->next->bookborrow->next->titlesize);
            fprintf(file,"%s\n",userbgn->list->next->bookborrow->next->title);
             fprintf(file,"%d\n",userbgn->list->next->bookborrow->next->authorsize);
             fprintf(file,"%s\n",userbgn->list->next->bookborrow->next->authors);
              fprintf(file,"%d\n",userbgn->list->next->bookborrow->next->year);
            userbgn->list->next->bookborrow->next=userbgn->list->next->bookborrow->next->next;
       }
       userbgn->list->next=userbgn->list->next->next;
    }
    return 0;
}



