
#ifndef BOOK_MANAGEMENT_GUARD_lo 
#define BOOK_MANAGEMENT_GUARD_lo

#include <stdio.h>
#include"structure.h"

extern BookList* bgn;
extern Userlist *userbgn;

//saves the database of books in the specified file
//returns 0 if books were stored correctly, or an error code otherwise
int store_books(FILE *file);


//loads the database of books from the specified file
//the file must have been generated by a previous call to store_books()
//returns 0 if books were loaded correctly, or an error code otherwise
int load_books(FILE *file);



//loads the database of users from the specified file
//the file must have been generated by a previous call to store_user()
//returns 0 if books were loaded correctly, or an error code otherwise
int load_user(FILE *file);

//saves the database of users in the specified file
//returns 0 if books were stored correctly, or an error code otherwise
int store_user(FILE *file);


//saves the database of books borrowing history in the specified file
//returns 0 if books were stored correctly, or an error code otherwise
int store_history(FILE *file);


//loads the database of books borrowing history from the specified file
//the file must have been generated by a previous call to store_history()
//returns 0 if books were loaded correctly, or an error code otherwise
int load_history(FILE* file);



//loads the database of the books being borrowed from the specified file
//the file must have been generated by a previous call to store_borrowed()
//returns 0 if books were loaded correctly, or an error code otherwise
int load_borrow(FILE* file);

//saves the database of the books being borrowed and not returned in the specified file
//returns 0 if books were stored correctly, or an error code otherwise
int store_borrowed(FILE *file);




#endif
