#include "projectheader.h"
#include<stdio.h>
#include<stdlib.h>
#include<string.h>


Book* bookfinal=0;
BookList *bgn=0;

//saves the database of books in the specified file
//returns 0 if books were stored correctly, or an error code otherwise
int store_books(FILE *file){
    Book* liststart=bgn->list->next;
   if (file == NULL ){
    printf("Error\nBook file does not exist: %s\n");
    exit(0);
}
while(bgn->list->next!=NULL){
    fprintf(file,"%d %s %s %d %d\n",bgn->list->next->id,bgn->list->next->title,bgn->list->next->authors,bgn->list->next->year,bgn->list->next->copies);
    bgn->list->next=bgn->list->next->next;
}
  bgn->list->next=liststart;
  return 0;
}

//loads the database of books from the specified file
//the file must have been generated by a previous call to store_books()
//returns 0 if books were loaded correctly, or an error code otherwise
int load_books(FILE *file){
     if (file == NULL ){
    printf("Error\nBook file does not exist: %s\n");
	return 1;
	exit(0);
     }
	 bookfinal=(Book*)malloc(sizeof(Book));
	
	bgn=(BookList*)malloc(sizeof(BookList));
    bgn->list=bookfinal;
    bgn->length=0;
    while (!feof(file))
	{		
		Book* book=(Book*)malloc(sizeof(Book));
		bookfinal->next=book;
        
        book->authors=(char *)malloc(100*sizeof(char));
        book->title=(char *)malloc(100*sizeof(char));
		
        fscanf(file,"%d %s %s %d %d\n",&book->id,book->title,book->authors,&book->year,&book->copies);
        bgn->length+=1;
        
         
        bookfinal=book;
		
		
	}
	bookfinal->next=NULL;
	return 0;
    
}

//adds a book to the ones available to the library
//returns 0 if the book could be added, or an error code otherwise
int add_book(Book book){
   
     Book* liststart=bgn->list->next;
     Book* aimbook=&book;
     int a=0;
    while(bgn->list->next!=NULL){
        if(strcmp(bgn->list->next->title,book.title)==0){
            a=1;
            break;
        }
    }
    if(a==1){
        bgn->list->next->copies+=1;
    }
    else{
    while(bgn->list->next!=NULL){
        bgn->list->next=bgn->list->next->next;
    }
    bgn->list->next=aimbook;
    bgn->list->next=liststart;
    }
    return 0;
}

//removes a book from the library
//returns 0 if the book could be successfully removed, or an error code otherwise.
int remove_book(Book book){

     if (bgn->list->next==NULL){
        printf("\nThis list is NULL\n");
        return -1;
     }
     Book* liststart=bgn->list->next;
    while(bgn->list->next!=NULL&&bgn->list->next->id!=book.id){
        bgn->list->next=bgn->list->next->next;
    }
    if(bgn->list->next->id==book.id){
        if(bgn->list->next==liststart){
            bgn->list->next=liststart->next;
        }
        else{
            bgn->list->next=bgn->list->next->next;
            bgn->list->next=liststart;
        }
        return 0;
        
    }
    else{
        printf("There is no assigned book in the list");
        return -1;
    }
    
}
     

//finds books with a given title.
//returns a BookList structure, where the field "list" is a list of books, or null if no book with the 
//provided title can be found. The length of the list is also recorded in the returned structure, with 0 in case
//list is the NULL pointer.
BookList find_book_by_title (const char *title){
   Book* liststart=bgn->list->next;
    BookList findbytitle;
    findbytitle.list=0;
   
    findbytitle.length=0; 
    Book* booknew=(Book*)malloc(sizeof(Book));
    Book* start=booknew;
    int a=0;
    for (int i=0; i< bgn->length; i++) {
			if (!strcmp(bgn->list->next->title, title)){  
                   
               booknew->id=bgn->list->next->id;
               booknew->year=bgn->list->next->year;
               booknew->copies=bgn->list->next->copies;
                 
                booknew->authors=bgn->list->next->authors;
                 booknew->title=bgn->list->next->title;
             
                 
               booknew->next=(Book*)malloc(sizeof(Book));
              booknew=booknew->next;
              a+=1;
            }
            bgn->list->next=bgn->list->next->next;
         
           	  
		}
        if(a==0){
            printf("\nError, no such title\n");
        }
        booknew=NULL;
        findbytitle.list=start;
        bgn->list->next=liststart;
       
        return findbytitle;
}

//finds books with the given authors.
//returns a Booklist structure, where the field "list" is a newly allocated list of books, or null if no book with the 
//provided title can be found. The length of the list is also recorded in the returned structure, with 0 in case
//list is the NULL pointer.
BookList find_book_by_author (const char *author){
    Book* liststart=bgn->list->next;
    BookList findbyauthor;
    findbyauthor.list=NULL;
    findbyauthor.length=0; 
    Book* booknew=(Book*)malloc(sizeof(Book));
    Book* start=booknew;
    int a=0;
    for (int i=0; i< bgn->length; i++) {
			if (!strcmp(bgn->list->next->authors, author)){  
                   
               booknew->id=bgn->list->next->id;
               booknew->year=bgn->list->next->year;
               booknew->copies=bgn->list->next->copies;
                 
                booknew->authors=bgn->list->next->authors;
                 booknew->title=bgn->list->next->title;
             
                 
               booknew->next=(Book*)malloc(sizeof(Book));
               booknew=booknew->next;
               a+=1;
            }
            bgn->list->next=bgn->list->next->next;
         
           	  
		}
        if(a==0){
            printf("\nError, no such author\n");
        }
        booknew=NULL;
        findbyauthor.list=start;
        bgn->list->next=liststart;
       
        return findbyauthor;
}


//finds books published in the given year.
//returns a Booklist structure, where the field "list" is a list of books, or null if no book with the 
//provided title can be found. The length of the list is also recorded in the returned structure, with 0 in case
//list is the NULL pointer.
BookList find_book_by_year (unsigned int year){
    Book* liststart=bgn->list->next;
    BookList findbyyear;
    findbyyear.list=0;
    findbyyear.length=0; 
    Book* booknew=(Book*)malloc(sizeof(Book));
    Book* start=booknew;
    int a=0;
    for (int i=0; i< bgn->length; i++) {
			if (bgn->list->next->year==year){  
                   
               booknew->id=bgn->list->next->id;
               booknew->year=bgn->list->next->year;
               booknew->copies=bgn->list->next->copies;
                 
                booknew->authors=bgn->list->next->authors;
                 booknew->title=bgn->list->next->title;
             
                 
               booknew->next=(Book*)malloc(sizeof(Book));
               booknew=booknew->next;
              a+=1;
            }
            bgn->list->next=bgn->list->next->next;
            
         
           	  
		}
        if(a==0){
            printf("\nError, no such year\n");
        }
        booknew=NULL;
        findbyyear.list=start;
        bgn->list->next=liststart;
       
        return findbyyear;
}



// int main( int argc, char **argv )
// {
//    FILE *fp=fopen("books.txt","r");
//    FILE *fp2=fopen("data3.txt","w");
//  if (fp == NULL ){
//     printf("Error\nBook file does not exist: %s\n");
// 	return 1;
// 	exit(0);
//      }
// 	load_books(fp);
//     fclose(fp);
//     char *xx="jiangsho";

//     store_books(fp2);
//     fclose(fp2);
  
//     BookList x=find_book_by_author(xx);
   
//     printf("%d %s %s %d %d\n",bgn->list->next->id,bgn->list->next->title,bgn->list->next->authors,bgn->list->next->year,bgn->list->next->copies);
//      printf("%d %s %s %d %d\n",x.list->id,x.list->title,x.list->authors,x.list->year,x.list->copies);
//       printf("%d %s %s %d %d",x.list->next->id,x.list->next->title,x.list->next->authors,x.list->next->year,x.list->next->copies);
      
// 	return 0;
    
// }
